/***************************************************************************************************************************************
****************************************************************************************************************************************
 * Team ID:     B34
 * Author List:	Sanjay A C, Vikas H C, Keerthana A B, Sucharitha Bhat J S. 	  
 * Filename:	RGB.h
 * Theme:		Search and Rescue
 * Functions:	color_sensor_pin_config,display_colour
 * Connection of RGB LED:
	*	RED	pin		- pin 20 : PD0
	*	Green pin	- pin 19 : PD1
	*	Blue pin	- pin 37 : PD3
	*	Ground pin	- pin 23
 ***************************************************************************************************************************************
 ***************************************************************************************************************************************
 */


#ifndef COLOUR_H_
#define COLOUR_H_
#include <math.h> //included to support power function


volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red;       // variable to store the pulse count when read_red function is called
volatile unsigned long int blue;      // variable to store the pulse count when read_blue function is called
volatile unsigned long int green;     // variable to store the pulse count when read_green function is called
volatile unsigned long int no_ff;     // variable to store the pulse count when no_filter function is called

/******************************************************************************************************************************
* Function Name: color_sensor_pin_config
* Input:		 none
* Output:		 none
* Logic:		 configure ports for RGB LED
* Example call:	 rgb_sensor_pin_config();
*******************************************************************************************************************************/

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFB; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x04;//Enable internal pull-up for PORTD 0 pin
}

/******************************************************************************************************************************
* Function Name: display_colour
* Input:		 c (colour to be displayed 0-RED, 1-GREEN, 2-Blue, 3-NO COLOUR)
* Output:		 none
* Logic:		 Turns on specified Colour of RGB LED
* Example call:	 display_colour();
*******************************************************************************************************************************/
/*
*	RED		- pin 20 : PD0
*	Green	- pin 19 : PD1
*	Blue	- pin 37 : PD3
*/
void display_colour(int c)
{
	//unsigned char a;
	switch(c)
	{
		case 0:	PORTD=PORTD & 0xF4;
				PORTD=PORTD | 0x01;break;
		
		case 1:	PORTD=PORTD & 0xF4;
				PORTD=PORTD | 0x02;break;
		
		case 2:
				PORTD=PORTD & 0xF4;
				PORTD=PORTD | 0x08;break;
		
		default:
		case 3:
				PORTD=PORTD & 0xF4;
				break;
	}		
}

#endif